proyecto/urls.py
from django.contrib import admin
from django.urls import path
from tasks import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home ,name='home'),
    path('signup/', views.signup,name='signup' ),
    path('logout/', views.desconectar,name='logout' ),
    path('iniciarSesion/', views.iniciarSesion,name='iniciarSesion' ),
    path('recuperar/', views.recuperar,name='recuperar' ),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="registration/reset_password.html"), name='reset_password'),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complet.html"), name='password_reset_complete'),
    path('productos/', views.lista_productos, name='lista_productos'),
    path('agregar_producto/', views.agregar_producto, name='agregar_producto'),
    path('editar_producto/<int:producto_id>',views.editar_producto,name='editar_producto'),
    path('productosB/<int:producto_id>',views.eliminar_producto,name='eliminar_producto'),
    path('clientes/',views.clientess,name='clientes'),
    path('agregar_clientes/', views.agregar_cliente, name='agregar_clientes'),
    path('clientesB/<int:clientes_id>/', views.borrar_clientes,name='borrar_clientes' ),
    path('editar_clientesB/<int:clientes_id>',views.editar_cliente,name='editar_cliente'),
    path('clientes/', views.lista_clientesss, name='lista_clientesss'),
    path('carrito/', views.carrito, name='carrito'),
    path('agregar_carrito/', views.agregar_al_carrito, name='agregar_carrito'),

    
]

    

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Productos(models.Model):
    codigo_producto = models.CharField(max_length=50)
    nombre_producto = models.CharField(max_length=100)
    categoria = models.CharField(max_length=50)
    descripcion = models.TextField(max_length=50)
    precio = models.DecimalField(max_digits=10, decimal_places=0)
    cantidad = models.PositiveIntegerField(null=True)
    def __str__(self):
        return self.nombre_producto
class Categoria(models.Model):
    nombre_categoria = models.CharField(max_length=50)
    descripcion_categoria = models.TextField(blank=True)
class clientes(models.Model):
    cedula = models.CharField(max_length=20,unique=True)
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)
    direccion = models.CharField(max_length=255)
    gmail = models.EmailField()
class Empleados(models.Model):
    cedula = models.CharField(max_length=20)
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)
    direccion = models.CharField(max_length=255)
    gmail = models.EmailField()
class Ventas(models.Model):
    OPCIONES=[
        ('debito', 'debito'),
        ('efectivo', 'efectivo'),
        ('tarjeta de credito', 'tarjeta de credito'),
        ('psi', 'psi'),
        ('nequi', 'nequi'), 
    ]
    subtotal = models.FloatField()
    fecha = models.DateTimeField(auto_now_add=True)
    hora = models.DateTimeField(auto_now_add=True)
    metodo_pago = models.CharField(max_length=50,choices=OPCIONES)
    total = models.FloatField()
    id_empleado = models.ForeignKey(Empleados, on_delete=models.CASCADE)
    id_producto = models.ForeignKey(Productos, on_delete=models.CASCADE)
class Stock(models.Model):
    cantidad_stock = models.IntegerField()
    fecha_revision = models.CharField(max_length=100)
    fecha_reposicion = models.CharField(max_length=100)
    id_producto = models.ForeignKey(Productos, on_delete=models.CASCADE)
class Carrito(models.Model):
    nomproducto = models.IntegerField(max_length=100)
    precio = models.CharField(max_length=100)
    cantidad = models.CharField(max_length=100)
    id_producto = models.ForeignKey(Productos, on_delete=models.CASCADE)
    


tasks/forms.py
from django.forms import ModelForm
from django import forms
from .models import Productos, clientes, Carrito

class producform(ModelForm):
    class Meta:
        model = Productos
        fields = ['codigo_producto', 'nombre_producto', 'categoria', 'descripcion','precio', 'cantidad']
class clientform(ModelForm):
    class Meta:
        model = clientes
        fields = ['cedula', 'nombres', 'apellidos', 'direccion','telefono', 'gmail']
class carritoform(ModelForm):
    class Meta:
        model = Carrito
        fields = ['nomproducto', 'precio', 'cantidad']
class AgregarAlCarritoForm(forms.Form):
    cantidad = forms.IntegerField(min_value=1, initial=1)

tasks/views.py
import re
from django.shortcuts import render, redirect ,get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from .models import Productos, clientes,Carrito
from .forms import producform, clientform, AgregarAlCarritoForm
from django.utils import timezone
from dotenv import load_dotenv
from email.message import EmailMessage
import os
import smtplib
import ssl
# Create your views here.

@login_required
def home(request):
    
    Producto = Productos.objects.all()
    return render(request, 'home.html',{'productos':Producto})

def is_valid_password(password):
    # La contraseña debe tener al menos 8 caracteres
    # Debe contener al menos una letra mayúscula, una letra minúscula y un carácter especial
    regex = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$')
    return bool(regex.match(password))

def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html', {'form': UserCreationForm})
    else:
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']
        if password1 == password2 and len(password1) >= 8 and is_valid_password(password1):
            try:
                user = User.objects.create_user(
                    username=request.POST['username'], password=password1,email=email)
                user.save()
                login(request, user)
                return redirect('tasks')
            except IntegrityError:
                return render(request, 'signup.html', {'form': UserCreationForm, 'error': 'El usuario ya existe'})
        return render(request, 'signup.html', {'form': UserCreationForm, 'error': 'La contraseña no cumple con los requisitos'})
    
def email(email):
    load_dotenv()
    email_sender = "martinezaleja180220@gmail.com"
    password =  os.getenv("PASSWORD")
    email_reciver = email
    subject = "NOTIFICACION INICIO DE SESION"
    body = f""" Un usuario esta ingresando al sistema
    (gmail de caracter informativo, no responder este gmail.)  {email_reciver}"""
    em = EmailMessage()
    em ["From"] = email_sender
    em ["To"] = email_reciver
    em ["Subject"] = subject
    em.set_content(body)
    context = ssl.create_default_context() 
    with smtplib.SMTP_SSL("smtp.gmail.com",465, context=context  ) as smtp:
        smtp.login(email_sender,password)
        smtp.sendmail(email_sender,email_reciver,em.as_string())  
    return

def recuperar(request):
    if request.method=='GET':
        return render(request,'recuperar.html')
    else: 
        usuario=User.objects.get(email=request.POST['correo']) 
        print(usuario.password)
        email() 
        return render(request,'recuperar.html',{
            'user':usuario.email
        })
    
@login_required
def desconectar(request):
    logout(request)
    return redirect('iniciarSesion')


def iniciarSesion(request):
    if request.method == 'GET':
        return render(request, 'iniciarSesion.html', {'form': AuthenticationForm})
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'iniciarSesion.html', {'form': AuthenticationForm, 'error': 'el usuario o la contraseña  es incorrecto'})
        else:
            login(request, user)
            email(user.email)
            return redirect('home')
        
@login_required
def lista_productos(request):
    productos = Productos.objects.all()
    query = request.POST.get('q')
    if query:
        productos = productos.filter(nombre_producto__icontains=query)
    return render(request, 'lista_productos.html', {'productos': productos})
        

@login_required
def agregar_producto(request):
    if request.method == 'GET':
        return render(request, 'agregar_producto.html', {'form': producform})
    else:
        try:
            form = producform(request.POST)
            new_produc = form.save(commit=False)
            new_produc.save()
            return redirect('lista_productos')
        except ValueError:
            return render(request, 'agregar_producto.html', {"form": producform, "error": "Error creating producto."})
        
@login_required        
def editar_producto(request, producto_id):
    if request.method == 'GET':
        producto = get_object_or_404(Productos, pk=producto_id)
        Form = producform(instance=producto)
        return render(request, 'editar_producto.html', {'producto': producto, 'form': Form})
    else:
        try:
            producto = get_object_or_404(Productos,pk=producto_id)
            form = producform(request.POST, instance=producto)
            form.save()
            return redirect('lista_productos')
        except ValueError:
            return render(request, 'editar_producto.html', {'producto': producto, 'form': form, 'error': 'Error actualizando task.'})
        
@login_required
def eliminar_producto(request, producto_id):
    productos = get_object_or_404(Productos, pk=producto_id)
    if request.method == 'POST':
        productos.delete()
        return redirect('lista_productos')
    
@login_required
def clientess(request):
    cliente = clientes.objects.all()
    if request.method == 'GET':
        return render(request,'clientes.html',{'clientes':cliente})
    
@login_required
def agregar_cliente(request):
    if request.method == 'GET':
        return render(request, 'agregar_clientes.html', {'form': clientform})
    else:
        try:
            form = clientform(request.POST)
            new_cliente = form.save(commit=False)
            new_cliente.save()
            return redirect('clientes')
        except ValueError:
            return render(request, 'agregar_clientes.html', {"form": clientform, "error": "Error creating producto."})

@login_required
def borrar_clientes(request, clientes_id):
    clientess = get_object_or_404(clientes, pk=clientes_id)
    if request.method == 'GET':
        clientess.delete()
        return redirect('clientes')

@login_required
def editar_cliente(request, clientes_id):
    if request.method == 'GET':
        clientess = get_object_or_404(clientes, pk=clientes_id)
        Form = clientform(instance=clientess)
        return render(request, 'editar_clientes.html', {'clientes': clientess, 'form': Form})
    else:
        try:
            clientess = get_object_or_404(clientes,pk=clientes_id)
            form = clientform(request.POST, instance=clientess)
            form.save()
            return redirect('clientes')
        except ValueError:
            return render(request, 'editar_clientes.html', {'clientes': clientess, 'form': form, 'error': 'Error actualizando task.'})

@login_required
def lista_clientesss(request):
    clientess = clientes.objects.all()
    query = request.POST.get('q')
    if query:
        clientess = clientess.filter(cedula__icontains=query)
    return render(request, 'clientes.html', {'clientes': clientess})

@login_required
def carrito(request):
    if request.method=='GET':
        productos = Productos.objects.all()
        return render(request,'carrito.html',{'productos':productos})
    else:
        productos = Productos.objects.filter(nombre_producto__icontains=request.POST['nombre'])
        return render(request,'carrito.html',{'productos':productos})
    
@login_required        
def agregar_al_carrito(request):
    if request.method == 'POST':
        form = AgregarAlCarritoForm(request.POST)
        if form.is_valid():
            producto_id = request.POST['producto_id']
            cantidad = request.POST['cantidad']
            producto = Productos.objects.get(pk=producto_id)
            Carrito.objects.create(id_producto=producto,nomproducto=1,precio=2500,cantidad=cantidad)
            return redirect('carrito')
    else:
        productos = Productos.objects.all()
        form = AgregarAlCarritoForm()
    return render(request, 'carrito.html', {'form': form,'productos':productos})

tasks/templates/agregar_clientes.html
<!DOCTYPE html>
<html>
<head>
    <title>Agregar clientes</title>
    {% extends 'base.html' %}
</head>
<body>
    <h1>Agregar Nuevo clientes</h1> 

{% block content %}

    <form action="/agregar_clientes/" method="POST">
        {% csrf_token %}
        {{form}}

        <button>
            save
        </button>

    </form>
{% endblock %}    
</body>
</html>

tasks/templates/agregar_producto.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Agregar Producto</title>
    <link rel="stylesheet" href="{% static 'css/agregar_producto.css' %}">
 
</head>
<body>
    <h1>Agregar Nuevo Producto</h1> 

{% block content %}

    <form action="/agregar_producto/" method="POST">
        {% csrf_token %}
        {{form}}

        <button>
            save
        </button>

    </form>
{% endblock %}    
</body>
</html>

tasks/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static 'js/carrito.js' %}"></script>

    <title>Login Proyecto</title>

    {% block css %}
    {% endblock %}

    {% block img %}
    {% endblock %}

</head>

<body>

    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="{% static 'css/base.css' %}">
      <title>Tienda Online</title>
    </head>
    <body>
    
      <header>
        <div class="logo">
          <img width="150" src="{% static 'css/logo_transparent.png' %}" >
        </div>
        <nav>
          <ul>
            {% if user.is_authenticated %}
              <li><a href="/agregar_producto/">Agregar productos</a></li>
              <li><a href="/productos/">Productos agregados</a></li>
              <li><a href="/clientes">Clientes</a></li>
              <li><a href="/carrito">Carrito </a></li>
              <li><a href="/logout">Salir</a></li>
            {% else %}
              <li><a href="/iniciarSesion">Iniciar sesión</a></li>
            {% endif %}
    
            {% if user.is_superuser %}
              <li><a href="/signup">Registrar usuario</a></li>
            {% endif %}
          </ul>
        </nav>
      </header>
    

    
    </body>
    </html>
    




    {% block content %}
    {% endblock %}


</body>

</html>

tasks/templates/carrito.html
{% extends 'base.html' %}

{% block content %}
    
<form method="post" action="/carrito/">
    {% csrf_token %}
    <input type="text" name="nombre" value="buscar" placeholder="buscar">
    <button>buscar</button>
</form>


{% for producto in productos %}
    <div>
            <form method="post" id="formulario" action="/agregar_carrito/">
                 {% csrf_token %}
            <input type="hidden" name="producto_id" value="{{ producto.id }}">
            <label for="nombre">Nombre producto:</label>
            <input type="text" name="nombre" value="{{producto.nombre_producto}}" readonly>
            <label for="precio">Precio:</label>
            <input type="text" name="precio" value="{{ producto.precio }}">

            <label for="id_cantidad">Cantidad:</label>
            <input class="inputText" type="number"  id="id_cantidad" name="cantidad" value="1" min="1">
            
            <button>Agregar</button>
          </form> 
        </form>
        
    </div>
    

{% endfor %}
<br>
<br>
<table id="transactionTable" border="3">
    <thead>
    <tr>
      <th>Nombre Producto</th>
      <th>Precio</th>
      <th>cantidad</th>
      <th>valor</th>
      
    </tr>
  </thead>
  <tbody>
    
  </tbody>
  <tfoot>
    <tr>
      <td colspan="3">Total</td>
      <td></td>
    </tr>
  </tfoot>
    
    <p><button id="reset">Reiniciar</button></p>
    
  </table>
    
{% endblock %}

tasks/templates/clientes.html
{% extends 'base.html' %}


{% block content %}
<form method="post" action="{% url 'lista_clientesss' %}">
    {% csrf_token %}
    <input type="number" name="q" placeholder="Buscar Cliente..." value="cedula">
    <button type="submit">Buscar</button>
</form>

    <div class="card-body">
        
        <div
            class="table-responsive">
            <table
                class="table table-striped table-hover table-borderless table-primary align-middle">
                <thead class="table-light">
                    <caption>
                        Clientes
                    </caption>
                    <tr>
                       
                        <th>Cedula</th>
                        <th>Nombre</th>
                        <th>Direccion</th>
                        <th>Telefono</th>
                        <th>Correo</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {% for cliente in clientes %}
                    <tr class="table-primary">
                       
                       
                        <td>{{cliente.cedula}}</td>
                        <td>{{cliente.nombres}} - {{cliente.apellidos}}</td>
                        <td>{{cliente.direccion}}</td>
                        <td>{{cliente.telefono}}</td>
                        <td>{{cliente.gmail}}</td>
                        <td><button><a href="{% url 'borrar_clientes' cliente.id %}">Eliminar</a></button></td>
                        <td><button><a href="{% url 'editar_cliente' cliente.id %}">Editar</a></button></td>
                                  
                    </tr>
                </tbody>

                



                {% endfor %}
            </table>
        </div>

        <form action="{% url 'agregar_clientes' %}" method="POST">
            {% csrf_token %}
            <button>     
            agregar
            </button>
        </form>
      

    </div>




{% endblock %}

tasks/templates/editar_clientes.html
<!DOCTYPE html>
<html>
<head>
    <title>Editar clientes</title>
    {% extends 'base.html' %}
</head>
<body>
    <h1>Editar clientes</h1>
    {% block content %}
      {{error}}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Modificacion</button>
    </form>
    {% endblock %}
</body>
</html>

tasks/templates/editar_producto.html
<!DOCTYPE html>
<html>
<head>
    <title>Editar Producto</title>
    {% extends 'base.html' %}
</head>
<body>
    <h1>Editar Productos</h1>
    {% block content %}
      {{error}}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Modificacion</button>
    </form>
    {% endblock %}
</body>
</html>

tasks/templates/iniciarSesion.html

{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/inicio_Sesion.css' %}">
{% endblock %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Classic Login Form Example</title>
  <link href="https://fonts.googleapis.com/css?family=Assistant:400,700" rel="stylesheet">
  <div class="header_logo">
    <img width="150" src="{% static 'css/logo_transparent.png' %}" >
  </div>

</head>
<body>

  {% block img %}
  {% endblock %}

    {% block content %}


    {{error}}
  <!-- partial:index.partial.html -->
  <section class='login' id='login'>
    <div class='head'>
      <h1 class='company'>Ingresa ¡Admin!</h1>
    </div>
    <p class='msg'>Bienvenido, estas de vuelta</p>
    <div class='form'>
      <form action="/iniciarSesion/" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder='Username' class='text' id='username' required><br>
        <input type="password" name="password" placeholder='••••••••••••••' class='password'><br>
        <button class='btn-login' id='do-login'>Iniciar</button>
        <a class="forgot" href="{% url 'reset_password' %}">¿olvido su contraseña?</a>
      </form>
    </div>
  </section>
  <!-- partial -->
  <footer>
    <p>RapidAle <span class='heart'>&hearts;</span> by Aleja Martinez(<a href='https://github.com/pxntxs'>@martinezaleja180220</a>)</p>
    <p>Link: <a href='https://uigradients.com/#Turquoiseflow'>https://github.com/ghostgirl1806/Proyecto.git</a></p>
  </footer>
  <script src="{% static 'script.js' %}"></script>
  {% endblock %}
</body>
</html>

tasks/templates/lista_clientes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de clientes</title>
</head>
<body>
    <h1>Lista de clientes</h1>
    <form method="post" action="{% url 'lista_clientess' %}">
        {% csrf_token %}
        <input type="text" name="q" placeholder="Buscar clientes..." value="nombre">
        <button type="submit">Buscar</button>
    </form>
    {% for cliente in clientes %}
        <p> clientes: {{ cliente.id }} - clientes: {{cliente.cedula}} - clientes: {{cliente.nombres}} - clientes: {{cliente.apellidos}} - clientes: {{cliente.direccion}} - clientes: {{cliente.telefono}}  - clientes: {{cliente.gmail}} </p>

    <form action="{% url 'agregar_cliente' clientes.id %}" method="POST">
        {% csrf_token %}
        <button>     
        agregar
        </button>
    </form>
    <form action="{% url 'eliminar_clientes' clientes.id %}" method="POST">
        {% csrf_token %}
        <button>Eliminar</button>
    </form>
    {% endfor %}
    <form action="/">
        <button>Volver</button>
    </form>
</body>
</html>
    </form>
</body>
</html>

tasks/templates/recuperar.html
{% extends 'base.html' %}

{% block content %}

    <h2>Recuperar Contraseña</h2>
{{user}}
    <form action="/recuperar/" method="POST" class="text-center">
        {% csrf_token %} 
        <label for="correo">Correo electrónico:</label>
        <input type="email" id="correo" name="correo" required>
        <button> ENVIAR</button>
    </form>



{% endblock %}

tasks/templates/signup.html
{% extends 'base.html' %}

{% block content %}

<h1>Alejaaaaaaaa</h1>
{{error}}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <label for="email">Correo Electronico </label>
    <input type="email" id="email" name="email" required>
    <p><button>
        boton
    </button></p>
</form>


{% endblock %}

tasks/templates/task_detail.html
{% extends 'base.html' %}

{% block content %}

{{task.title}}

{{error}}

<form method="POST">
  {% csrf_token %}
  {{form.as_p}}

  <button>
    Update
  </button>
</form>

<form action="{% url 'complete_task' task.id %}" method="POST">
  {% csrf_token %}
  
  <button>
    complete
  </button>
</form>

<form action="{% url 'delete_task' task.id %}" method="POST">
  {% csrf_token %}
  
  <button>
    delete
  </button>
</form>

{% endblock %}

tasks/templates/tasks.html
{% extends 'base.html' %}

{% block content %}

<h1> tasks bienvenidooo</h1>

<ul>
    {% for tasks in task %}
    <li>
        <a href="{% url 'task_detail' task.id %}">
            {% if task.important %}
            <strong> {{task.title}} </strong>
            {% else %}
            {{task.title}}
            {% endif %}
            <p> {{task.description}}</p>
            <p> {{task.user.username}}</p>
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}